name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean verify

      - name: Run SonarCloud Analysis
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: cc9cd7a9bedd3f93f207160d9716128bc72adb1f
